export enum Element {
    FIRST_FORM_ANY = 0,
    FIRST_FORM_ANY_SUBMIT,
    
    USER_PROFILE_CREATION_TITLE,
    UPC_FIRST_NAME,
    UPC_FIRST_NAME_LABEL,
    UPC_LAST_NAME,
    UPC_LAST_NAME_LABEL,
    UPC_EMAIL,
    UPC_EMAIL_LABEL,
    UPC_PASSWORD,
    UPC_PASSWORD_LABEL,
    UPC_CONFIRM_PASSWORD,
    UPC_CONFIRM_PASSWORD_LABEL,
    UPC_GENDER_MALE,
    UPC_GENDER_FEMALE,
    UPC_GENDER_UNDISCLOSED,
    UPC_GENDER_LABEL,
    UPC_DATE_OF_BIRTH,
    UPC_DATE_OF_BIRTH_LABEL,
    UPC_PHONE_NUMBER,
    UPC_PHONE_NUMBER_LABEL,
    UPC_ADDRESS,
    UPC_ADDRESS_LABEL,
    UPC_LINKEDIN,
    UPC_LINKEDIN_LABEL,
    UPC_GITHUB,
    UPC_GITHUB_LABEL,
    UPC_SUBMIT
}

export function getElementByName(name: string): Element | undefined {
  if (name in Element) return Element[name as keyof typeof Element];
  return undefined;
}
