export enum Element {
    FIRST_FORM_ANY = 0,
    FIRST_FORM_ANY_SUBMIT,
    
    USER_PROFILE_CREATION_TITLE,
    UPC_FIRST_NAME,
    UPC_LAST_NAME,
    UPC_EMAIL,
    UPC_PASSWORD,
    UPC_CONFIRM_PASSWORD,
    UPC_GENDER_MALE,
    UPC_GENDER_FEMALE,
    UPC_GENDER_UNDISCLOSED,
    UPC_DATE_OF_BIRTH,
    UPC_PHONE_NUMBER,
    UPC_ADDRESS,
    UPC_LINKEDIN,
    UPC_GITHUB,
    UPC_SUBMIT
}